import Template from "./Template"

import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
}

export default async function Home() {
  return <Template />
}
